replicaCount: 2

image:
  repository: karna9/devsecops-demo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: vite.local
      paths:
        - path: /
          pathType: Prefix
  tls: []