replicaCount: 2

image:
  repository: ghcr.io/karna-maddali/devsecops
  tag: sha-c7419117fc6db7aec1dabe7c254b737c21224ce3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  # If host is empty, Ingress will accept any host (useful for testing)
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
