replicaCount: 2

image:
  repository: ghcr.io/karna-maddali/devsecops
  tag: sha-f90fd81a0a6b54a103be1defbe353b9a5d3c4a16
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  # If host is empty, Ingress will accept any host (useful for testing)
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []
